export enum ConsignmentType {
  REMESSA_ELETIVO = 'CONSIGNADO - REMESSA ELETIVO',
  REMESSA_FIXO = 'CONSIGNADO - REMESSA FIXO',
  AJUSTE_C1 = 'CONSIGNADO - AJUSTE C1 C/ MOV ESTOQUE S/WMS',
  AJUSTE_C5 = 'CONSIGNADO - AJUSTE C5 C/ MOV ESTOQUE S/WMS',
  RETORNO = 'CONSIGNADO - RETORNO',
  RETORNO_SIMBOLICO = 'CONSIGNADO - RETORNO SIMBOLICO C/ MOV ESTOQUE S/WMS',
}

export enum ConsignmentTypeDevolution {
  RETORNO = 'CONSIGNADO - RETORNO',
  RETORNO_SIMBOLICO = 'CONSIGNADO - RETORNO SIMBOLICO C/ MOV ESTOQUE S/WMS',
}
