export enum EProductItemStatus {
  IN_ELFA_STOCK = 'ESTOQUE_ELFA',
  AWAITING_DELIVERY = 'AGUARDANDO_ENTREGA',
  IN_CLIENT_STOCK = 'ESTOQUE_CLIENTE',
  STOCK_DISCREPANCY = 'DIVERGENCIA_ESTOQUE',
  CONSUMED = 'CONSUMIDO',

  PROCESSING_INVOICED = 'PROCESSANDO_FATURAMENTO',

  PRE_INVOICED = 'PRE_FATURADO',
  FAILED_PRE_INVOICED = 'NAO_PRE_FATURADO',

  INVOICED = 'FATURADO',
  FAILED_INVOICED = 'NAO_FATURADO',

  REVERSED = 'ESTORNADO',
}
