import { Global, Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { Order } from '@/entities/order.entity';
import { Store } from '@/entities/store.entity';
import { OrderProduct } from '@/entities/order-product.entity';
import {
  Antenna,
  Client,
  Invoice,
  Movement,
  Printer,
  PrintLot,
  Product,
  ProductConsumedGridView,
  ProductGridView,
  ProductItem,
  ProductItemDetailView,
  ProductItemTag,
  ProductMetricsView,
  Devolution,
  DevolutionProductIten,
  Warehouse,
  PreInvoicing,
  ApiLog,
  ProductPrintView,
  ProductInventoryLog,
  ProductHistory,
  StoreSummaryView,
  ProductItemDetailViewAll,
  Divergence,
  StateView,
  SellerView,
} from '../entities';
import { PreInvoicingProduct } from '@/entities/pre-invoice.product.entity';

@Global()
@Module({
  imports: [
    TypeOrmModule.forFeature([
      Client,
      Store,
      Antenna,
      Order,
      Product,
      OrderProduct,
      Movement,
      ProductItem,
      ProductItemTag,
      Warehouse,
      Printer,
      PrintLot,
      Invoice,
      ProductGridView,
      ProductItemDetailView,
      ProductMetricsView,
      ProductConsumedGridView,
      Devolution,
      DevolutionProductIten,
      PreInvoicing,
      PreInvoicingProduct,
      ApiLog,
      ProductPrintView,
      ProductInventoryLog,
      ProductHistory,
      StoreSummaryView,
      ProductItemDetailViewAll,
      Divergence,
      StateView,
      SellerView,
    ]),
  ],
  exports: [
    TypeOrmModule.forFeature([
      Client,
      Store,
      Antenna,
      Order,
      Product,
      OrderProduct,
      Movement,
      ProductItem,
      ProductItemTag,
      Warehouse,
      Printer,
      PrintLot,
      Invoice,
      ProductGridView,
      ProductItemDetailView,
      ProductMetricsView,
      ProductConsumedGridView,
      Devolution,
      DevolutionProductIten,
      PreInvoicing,
      PreInvoicingProduct,
      ApiLog,
      ProductPrintView,
      ProductInventoryLog,
      ProductHistory,
      StoreSummaryView,
      ProductItemDetailViewAll,
      Divergence,
      StateView,
      SellerView,
    ]),
  ],
})
export class RepositoryModule {}
